name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run test
        run: |
          yarn
          yarn lint

  test-ios-newarch:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache pods
        uses: actions/cache@v4
        with:
          path: |
            packages/RNExternalDisplayExample/ios/Pods
            packages/RNExternalDisplayExample/ios/build
          key: ${{ runner.os }}-pods-newarch-${{ hashFiles('**/packages/RNExternalDisplayExample/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-newarch-
      - name: Install deps
        run: yarn
      - name: Build RNExternalDisplayExample
        env:
          RCT_NEW_ARCH_ENABLED: 1
        run: |
          cd packages/RNExternalDisplayExample/ios
          pod repo update
          pod install
          cd ..
          xcodebuild -workspace ios/RNExternalDisplayExample.xcworkspace -scheme RNExternalDisplayExample -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build

  test-ios-oldarch:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache pods
        uses: actions/cache@v4
        with:
          path: |
            packages/RNExternalDisplayExample/ios/Pods
            packages/RNExternalDisplayExample/ios/build
          key: ${{ runner.os }}-pods-oldarch-${{ hashFiles('**/RNExternalDisplayExample/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-oldarch-
      - name: Install deps
        run: yarn
      - name: Build RNExternalDisplayExample
        env:
          RCT_NEW_ARCH_ENABLED: 0
        run: |
          cd packages/RNExternalDisplayExample/ios
          pod repo update
          pod install
          cd ..
          xcodebuild -workspace ios/RNExternalDisplayExample.xcworkspace -scheme RNExternalDisplayExample -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
  
  test-android-newarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      # - name: Setup Android Emulator
      #   run: |
      #     $ANDROID_HOME/tools/bin/sdkmanager --install emulator
      #     $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-28;google_apis;x86"
      #     echo no | $ANDROID_HOME/tools/bin/avdmanager create avd --force -n Test -k "system-images;android-28;google_apis;x86"
      #     $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
      - name: Install deps
        run: yarn
      - name: Build RNExternalDisplayExample
        run: |
          cd packages/RNExternalDisplayExample/android
          ./gradlew assemblerelease

  test-android-oldarch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Install deps
        run: yarn
      - name: Build RNExternalDisplayExample
        run: |
          cd packages/RNExternalDisplayExample/android
          sed -i 's/newArchEnabled=true/newArchEnabled=false/g' gradle.properties
          ./gradlew assemblerelease
